version: "3"
services: 
  mysql: 
    image: mysql
    ports: 
      - "3306:3306"
    container_name: mysql-container 
    environment: 
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
  redis: 
    image: redis
    ports: 
      - "6379:6379"
    container_name: redis-container
    command: 
      redis-server 
