version: "3"
services: 
  mysql: 
    image: mysql
    ports: 
      - "3306:3306"
    container_name: mysql-container 
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes: 
      - "${MYSQL_DIR}/data:/var/lib/mysql" #d挂载数据目录
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d" #挂载配置文件目录 
  redis: 
    image: redis
    ports: 
      - "6379:6379"
    container_name: redis-container 
