version: "3"
services: 
  mysql: 
    image: mysql:5.7
    ports: 
      - "3306:3306"
    container_name: mysql-container 
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes: 
      - "${MYSQL_DIR}/data:/var/lib/mysql" #d挂载数据目录
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d" #挂载配置文件目录 
  redis: 
    image: redis
    ports: 
      - "6379:6379"
    container_name: redis-container 
  etcd:
    image: quay.io/coreos/etcd:v3.3.12
    container_name: etcd-v3-contaniner
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - /Users/sxf/dockerYamlConfig/etcd-data:/etcd-data
    command:
      - "/usr/local/bin/etcd"
      - "--name"
      - "s1"
      - "--data-dir"
      - "/etcd-data"
      - "--advertise-client-urls"
      - "http://0.0.0.0:2379"
      - --listen-client-urls
      - "http://0.0.0.0:2379"
      - "--initial-advertise-peer-urls"
      - "http://0.0.0.0:2380"
      - "--listen-peer-urls"
      - "http://0.0.0.0:2380"
      - "--initial-cluster-token"
      - "tkn"
      - "--initial-cluster"
      - "s1=http://0.0.0.0:2380"
      - "--initial-cluster-state"
      - "new"
